### PR TITLE
Rely on alignment of usize or T

### LINKED ISSUE #16: Unexpected semver breaking: after 0.6.3, `im::Vector` is no longer considered an "indirection" for the purposes of recursive types.
This structure compiles on 0.6.2 but not 0.6.3:

```rust
pub enum Value {
    Int(U256),
    Bytes(im::Vector<u8>),
    Vector(im::Vector<Value>),
}
```

On 0.6.3 this says

```
recursive type `Value` has infinite size
```

Did 0.6.3 add some sort of small-vector optimization?

### PR DESCRIPTION
**Pull request by kornelski**
Fixes #16

### CODE REVIEW

**Comment by kornelski** [comment]
cc @vorner

File: src/inline_array/mod.rs [hunk 1]
```diff
@@ -88,6 +89,10 @@ pub struct InlineArray<A, T> {
     // 3 start at the beginning of the struct and that all of them are aligned to their maximum
     // alignment.
     //
+    // Unfortunately, we can't use `[A; 0]` to align to actual alignment of the type A, because
+    // it prevents use of InlineArray in recursive types.
+    // We rely on alignment of usize or T to be sufficient, and panic otherwise.
```
Comment (vorner) [inline src/inline_array/mod.rs:94]: Just to check, if I create `im::Vector<BigAlign>`, will that panic on me, or will it just figure out to store things out of line? Sorry, I don't have these details memorized any more.

Is panicking a different semver-breaking change, or is it fine this time? Or should we just declare a new version?

File: src/inline_array/mod.rs [hunk 2]
```diff
@@ -608,15 +627,68 @@ mod test {
...
-    fn big_align_elem() {
+    #[should_panic(
+        expected = "InlineArray can't satisfy alignment of sized_chunks::inline_array::test::unsufficient_alignment2::BigAlign"
+    )]
+    fn unsufficient_alignment2() {
         #[repr(align(256))]
         struct BigAlign(usize);
 
         let mut chunk: InlineArray<BigAlign, [usize; 256]> = InlineArray::new();
         chunk.push(BigAlign(42));
```
Comment (vorner) [inline src/inline_array/mod.rs:658]: AFAIK the part that'll panic is the `InlineArray::new()`. But this tests suggests the intention is to panic in push?

File: src/inline_array/mod.rs (hunk 1 above)
Comment (kornelski) [reply src/inline_array/mod.rs:94]: It panics. This struct never had out-of-line storage, so I didn't want to introduce a completely new behavior. Large alignments were unsound with 0.6.2, so this isn't breaking anything that wasn't already broken in 0.6.2.

File: src/inline_array/mod.rs (hunk 2 above)
Comment (kornelski) [reply src/inline_array/mod.rs:658]: I wasn't sure when it should panic. It'd be possible to just set CAPACITY=0 when alignment is wrong, and this would make `new` succeed and fail only at `push`.

File: src/inline_array/mod.rs (hunk 1 above)
Comment (vorner) [reply src/inline_array/mod.rs:94]: Hmm, probably. It's better to panic than to UB. But I think long-term, we want `im::Vector<BigAlign>` to Just Work. Panicking in the push (and anything else that adds elements) might make the `Vector` work, if it checks the capacity, though.
